services:
  redis:
    image: redis:latest # Using a lightweight Redis image
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    tty: true
    stdin_open: true
    environment:
      REDIS_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/data # Persist Redis data
    networks:
      - redis-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540" # Access RedisInsight on http://localhost:5540
    volumes:
      - redis-insight:/data # Persist RedisInsight data (e.g., connection details, workbench history)
    networks:
      - redis-network
    depends_on:
      - redis # Ensure Redis starts before RedisInsight

volumes:
  redis:
    driver: local
  redis-insight:
    driver: local

networks:
  redis-network:
    driver: bridge