services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: "rabbitmq_cookie"
      RABBITMQ_HOSTNAME: rabbitmq
      RABBITMQ_NODE_RAM_CACHE_SIZE: "60%"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - rabbitmq_network

volumes:
  rabbitmq-data:
    driver: local
  rabbitmq-log:
    driver: local

networks:
  rabbitmq_network:
    driver: bridge