user nginx;
worker_processes auto;

error_log /log/error.log notice;
pid       /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8088;
        charset utf8;

        location / {
            root /usr/share/nginx/html;
        }

        location /common-server {
            proxy_pass http://common-server/;
        }
    }
}

upstream common-server {
    server localhost:3001;
    server localhost:3002;
    server localhost:3003;
    server localhost:9010;
    server localhost:60050;
}