services:
  mysql1:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Пароль root (берётся из .env)
      MYSQL_DATABASE: ${MYSQL_DATABASE}             # Имя БД для создания (из .env)
      MYSQL_USER: ${MYSQL_USER}                     # Дополнительный пользователь БД (из .env)
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             # Пароль доп. пользователя (из .env)
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql_data1:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - app-network

  mysql2:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Пароль root (берётся из .env)
      MYSQL_DATABASE: ${MYSQL_DATABASE}             # Имя БД для создания (из .env)
      MYSQL_USER: ${MYSQL_USER}                     # Дополнительный пользователь БД (из .env)
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             # Пароль доп. пользователя (из .env)
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql_data2:/var/lib/mysql
    ports:
      - "33062:3306"
    networks:
      - app-network

  mysql3:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Пароль root (берётся из .env)
      MYSQL_DATABASE: ${MYSQL_DATABASE}             # Имя БД для создания (из .env)
      MYSQL_USER: ${MYSQL_USER}                     # Дополнительный пользователь БД (из .env)
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             # Пароль доп. пользователя (из .env)
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql_data3:/var/lib/mysql
    ports:
      - "33063:3306"
    networks:
      - app-network

  mysql-router:
    image: mysql/mysql-router:8.0
    environment:
      MYSQL_HOST: mysql1 # Hostname of one of the MySQL instances for bootstrapping
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_INNODB_CLUSTER_MEMBERS: 3 # Number of expected cluster members
    ports:
      - "6446:6446" # Default port for MySQL Router's read-write access
      - "6447:6447" # Default port for MySQL Router's read-only access
    depends_on:
      - mysql1
      - mysql2
      - mysql3
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest    # Образ phpMyAdmin
    container_name: myadmin     # Имя контейнера phpMyAdmin
    depends_on:
      - db                      # Сначала должен стартовать контейнер db
    ports:
      - "8080:80"               # phpMyAdmin будет доступен на порту 8080
    environment:
      PMA_HOST: db              # Хост БД для подключения (имя сервиса MySQL)
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Пароль root для доступа
    networks:
      - app-network

volumes:
  mysql_data1:
  mysql_data2:
  mysql_data3:

networks:
  app-network: