services:
  mysql1:
    image: mysql/mysql-server:8.0
    container_name: mysql1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Пароль root (берётся из .env)
      MYSQL_DATABASE: ${MYSQL_DATABASE}             # Имя БД для создания (из .env)
      MYSQL_USER: ${MYSQL_USER}                     # Дополнительный пользователь БД (из .env)
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             # Пароль доп. пользователя (из .env)
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql_data1:/var/lib/mysql
    ports:
      - "33061:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mysql2:
    image: mysql/mysql-server:8.0
    container_name: mysql2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Пароль root (берётся из .env)
      MYSQL_DATABASE: ${MYSQL_DATABASE}             # Имя БД для создания (из .env)
      MYSQL_USER: ${MYSQL_USER}                     # Дополнительный пользователь БД (из .env)
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             # Пароль доп. пользователя (из .env)
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql_data2:/var/lib/mysql
    ports:
      - "33062:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mysql3:
    image: mysql/mysql-server:8.0
    container_name: mysql3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Пароль root (берётся из .env)
      MYSQL_DATABASE: ${MYSQL_DATABASE}             # Имя БД для создания (из .env)
      MYSQL_USER: ${MYSQL_USER}                     # Дополнительный пользователь БД (из .env)
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             # Пароль доп. пользователя (из .env)
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql_data3:/var/lib/mysql
    ports:
      - "33063:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mysql-router:
    image: mysql/mysql-router:8.0
    container_name: mysql-router
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql1 # Hostname of one of the MySQL instances for bootstrapping
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_INNODB_CLUSTER_MEMBERS: 3 # Number of expected cluster members
    ports:
      - "6446:6446" # Default port for MySQL Router's read-write access
      - "6447:6447" # Default port for MySQL Router's read-only access
    healthcheck:
      test: ["CMD", "mysqlrouter", "--status"] # Check MySQL Router's status
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Give MySQL Router time to start and connect
    depends_on:
      - mysql1
      - mysql2
      - mysql3
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest    # Образ phpMyAdmin
    container_name: myadmin     # Имя контейнера phpMyAdmin
    restart: unless-stopped
    depends_on:
      - mysql-router            # Сначала должен стартовать контейнер mysql-router
    ports:
      - "8080:80"               # phpMyAdmin будет доступен на порту 8080
    environment:
      PMA_HOST: mysql-router                       # Хост БД для подключения (имя сервиса MySQL)
      PMA_PORT: 6446                               # Port exposed by MySQL Router
      PMA_ARBITRARY: 1                             # Allow connecting to arbitrary servers
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Пароль root для доступа
    networks:
      - app-network

volumes:
  mysql_data1:
  mysql_data2:
  mysql_data3:

networks:
  app-network: